"""This file is AUTO-GENERATED by langgen.py. DO NOT EDIT DIRECTLY."""

import json
import os
from enum import Enum


class Lang(Enum):
    """Enum representing available languages with their file paths."""
    ENGLISH = "assets/languages/english.json"
    GERMAN = "assets/languages/german.json"
    HUNGARIAN = "assets/languages/hungarian.json"

    def text(self):
        """Returns a LangText instance for this language."""
        return LangText(self)


class LangText:
    """Dynamically loads language texts based on the selected Lang enum value."""

    def __init__(self, lang_enum: Lang):
        self._text_data = {}
        lang_path = lang_enum.value
        try:
            if not os.path.isabs(lang_path):
                lang_path = os.path.join(
                    os.path.dirname(os.path.abspath(__file__)),
                    lang_path,
                )
            # The value of the enum is the filepath
            with open(lang_path, "r", encoding="utf-8") as f:
                self._text_data = json.load(f)
        except FileNotFoundError:
            print(f"ERROR: Language file {lang_path} not found.")
        except json.JSONDecodeError:
            print(f"ERROR: Language file {lang_path} has invalid JSON.")

    # 2. Generate properties for all keys
    @property
    def add_glossaries_title(self):
        """Default value: Adding dictionaries. Exit with #."""
        return self._text_data.get("add_glossaries_title", "MISSING TEXT KEY: add_glossaries_title")

    @property
    def add_words_title(self):
        """Default value: Adding words. Exit with #."""
        return self._text_data.get("add_words_title", "MISSING TEXT KEY: add_words_title")

    @property
    def all_done(self):
        """Default value: Done! Nothing left to practice!"""
        return self._text_data.get("all_done", "MISSING TEXT KEY: all_done")

    @property
    def already_learned(self):
        """Default value: You already know this word, there is another so..."""
        return self._text_data.get("already_learned", "MISSING TEXT KEY: already_learned")

    @property
    def boosted_confirm(self):
        """Default value: {} boosted: set to {} points!"""
        return self._text_data.get("boosted_confirm", "MISSING TEXT KEY: boosted_confirm")

    @property
    def check_state_type(self):
        """Default value: 
Do you want to check the status of a specific ..."""
        return self._text_data.get("check_state_type", "MISSING TEXT KEY: check_state_type")

    @property
    def checking_doubles(self):
        """Default value: Checking for doubles..."""
        return self._text_data.get("checking_doubles", "MISSING TEXT KEY: checking_doubles")

    @property
    def choose_number(self):
        """Default value: Choose ({}-{}): """
        return self._text_data.get("choose_number", "MISSING TEXT KEY: choose_number")

    @property
    def choose_word_form(self):
        """Default value: Choose a word type!"""
        return self._text_data.get("choose_word_form", "MISSING TEXT KEY: choose_word_form")

    @property
    def close_but_wrong(self):
        """Default value: Almost correct, try again!"""
        return self._text_data.get("close_but_wrong", "MISSING TEXT KEY: close_but_wrong")

    @property
    def conversion_error(self):
        """Default value: {} error in {} function! Please report it to th..."""
        return self._text_data.get("conversion_error", "MISSING TEXT KEY: conversion_error")

    @property
    def correct_answer(self):
        """Default value: Correct!"""
        return self._text_data.get("correct_answer", "MISSING TEXT KEY: correct_answer")

    @property
    def correct_detail(self):
        """Default value: Correct!"""
        return self._text_data.get("correct_detail", "MISSING TEXT KEY: correct_detail")

    @property
    def details_separator(self):
        """Default value: Additional correct answers: {}"""
        return self._text_data.get("details_separator", "MISSING TEXT KEY: details_separator")

    @property
    def done_message(self):
        """Default value: Done!"""
        return self._text_data.get("done_message", "MISSING TEXT KEY: done_message")

    @property
    def enter_expression(self):
        """Default value: Enter the expression: """
        return self._text_data.get("enter_expression", "MISSING TEXT KEY: enter_expression")

    @property
    def enter_glossary_name(self):
        """Default value: 
Enter the dictionary name: """
        return self._text_data.get("enter_glossary_name", "MISSING TEXT KEY: enter_glossary_name")

    @property
    def enter_learnlang_word(self):
        """Default value: Enter the {} expression: """
        return self._text_data.get("enter_learnlang_word", "MISSING TEXT KEY: enter_learnlang_word")

    @property
    def enter_mlang_word(self):
        """Default value: 
Enter the {} expression: """
        return self._text_data.get("enter_mlang_word", "MISSING TEXT KEY: enter_mlang_word")

    @property
    def enter_word_for_lang(self):
        """Default value: Enter the word/expression in {}-language:"""
        return self._text_data.get("enter_word_for_lang", "MISSING TEXT KEY: enter_word_for_lang")

    @property
    def error_opening_glossaries(self):
        """Default value:  - by opening glossaries.txt"""
        return self._text_data.get("error_opening_glossaries", "MISSING TEXT KEY: error_opening_glossaries")

    @property
    def error_reading_glossary(self):
        """Default value:  - by reading {}"""
        return self._text_data.get("error_reading_glossary", "MISSING TEXT KEY: error_reading_glossary")

    @property
    def glossary_exists(self):
        """Default value: This dictionary already exists!
Enter the name ..."""
        return self._text_data.get("glossary_exists", "MISSING TEXT KEY: glossary_exists")

    @property
    def glossary_too_long(self):
        """Default value: The dictionary named {} has more than 50 items!"""
        return self._text_data.get("glossary_too_long", "MISSING TEXT KEY: glossary_too_long")

    @property
    def goodbye(self):
        """Default value: Goodbye! :)"""
        return self._text_data.get("goodbye", "MISSING TEXT KEY: goodbye")

    @property
    def incorrect_detail(self):
        """Default value: Incorrect. The solution is: {}"""
        return self._text_data.get("incorrect_detail", "MISSING TEXT KEY: incorrect_detail")

    @property
    def incorrect_word(self):
        """Default value: Incorrect. The solution(s): {}"""
        return self._text_data.get("incorrect_word", "MISSING TEXT KEY: incorrect_word")

    @property
    def invalid_input_prompt(self):
        """Default value: Invalid answer, please try again! [ENTER]"""
        return self._text_data.get("invalid_input_prompt", "MISSING TEXT KEY: invalid_input_prompt")

    @property
    def max_points_confirm(self):
        """Default value: Points maxed out! {} completed!"""
        return self._text_data.get("max_points_confirm", "MISSING TEXT KEY: max_points_confirm")

    @property
    def max_points_word_complete(self):
        """Default value: Points maxed out! Word completed!"""
        return self._text_data.get("max_points_word_complete", "MISSING TEXT KEY: max_points_word_complete")

    @property
    def menu(self):
        """Default value: 
Welcome to the language learning program!
What..."""
        return self._text_data.get("menu", "MISSING TEXT KEY: menu")

    @property
    def menu_add_words(self):
        """Default value: Add new words"""
        return self._text_data.get("menu_add_words", "MISSING TEXT KEY: menu_add_words")

    @property
    def menu_check_progress(self):
        """Default value: Check my progress"""
        return self._text_data.get("menu_check_progress", "MISSING TEXT KEY: menu_check_progress")

    @property
    def menu_create_dictionaries(self):
        """Default value: Create new dictionaries"""
        return self._text_data.get("menu_create_dictionaries", "MISSING TEXT KEY: menu_create_dictionaries")

    @property
    def menu_exit(self):
        """Default value: Log out"""
        return self._text_data.get("menu_exit", "MISSING TEXT KEY: menu_exit")

    @property
    def menu_practice(self):
        """Default value: Practice"""
        return self._text_data.get("menu_practice", "MISSING TEXT KEY: menu_practice")

    @property
    def menu_settings(self):
        """Default value: Settings"""
        return self._text_data.get("menu_settings", "MISSING TEXT KEY: menu_settings")

    @property
    def menu_word_search(self):
        """Default value: Word search"""
        return self._text_data.get("menu_word_search", "MISSING TEXT KEY: menu_word_search")

    @property
    def min_langs_error(self):
        """Default value: Error: You must select at least 2 languages to ..."""
        return self._text_data.get("min_langs_error", "MISSING TEXT KEY: min_langs_error")

    @property
    def multiple_options_error(self):
        """Default value: 
More than one option is available ({})!
Please..."""
        return self._text_data.get("multiple_options_error", "MISSING TEXT KEY: multiple_options_error")

    @property
    def no_char(self):
        """Default value: n"""
        return self._text_data.get("no_char", "MISSING TEXT KEY: no_char")

    @property
    def nothing_to_practice(self):
        """Default value: Nothing to practice here yet..."""
        return self._text_data.get("nothing_to_practice", "MISSING TEXT KEY: nothing_to_practice")

    @property
    def practice_mode_select(self):
        """Default value: You can exit auto-continue mode with #.
Do you ..."""
        return self._text_data.get("practice_mode_select", "MISSING TEXT KEY: practice_mode_select")

    @property
    def select_active_langs(self):
        """Default value: Please select the languages you wish to practic..."""
        return self._text_data.get("select_active_langs", "MISSING TEXT KEY: select_active_langs")

    @property
    def select_answer_langs(self):
        """Default value: Select the language(s) you want to translate th..."""
        return self._text_data.get("select_answer_langs", "MISSING TEXT KEY: select_answer_langs")

    @property
    def select_question_lang(self):
        """Default value: Select the language in which the words will be ..."""
        return self._text_data.get("select_question_lang", "MISSING TEXT KEY: select_question_lang")

    @property
    def similar_words_title(self):
        """Default value: 
Similar words:"""
        return self._text_data.get("similar_words_title", "MISSING TEXT KEY: similar_words_title")

    @property
    def state_details_prompt(self):
        """Default value: Do you want to see all the details as well? ({}) """
        return self._text_data.get("state_details_prompt", "MISSING TEXT KEY: state_details_prompt")

    @property
    def state_options(self):
        """Default value: ['s', 'a']"""
        return self._text_data.get("state_options", "MISSING TEXT KEY: state_options")

    @property
    def state_score_group(self):
        """Default value: 
Words with {} points: {} pcs"""
        return self._text_data.get("state_score_group", "MISSING TEXT KEY: state_score_group")

    @property
    def state_summary(self):
        """Default value: 
Number of words: {}; number of completed words..."""
        return self._text_data.get("state_summary", "MISSING TEXT KEY: state_summary")

    @property
    def state_which_lang(self):
        """Default value: Which language's points do you want to see? ({}..."""
        return self._text_data.get("state_which_lang", "MISSING TEXT KEY: state_which_lang")

    @property
    def successfully_added(self):
        """Default value: Successfully added!"""
        return self._text_data.get("successfully_added", "MISSING TEXT KEY: successfully_added")

    @property
    def summary(self):
        """Default value: You reached the end. Correct answers: {}, incor..."""
        return self._text_data.get("summary", "MISSING TEXT KEY: summary")

    @property
    def warning_title(self):
        """Default value: 
Warning!"""
        return self._text_data.get("warning_title", "MISSING TEXT KEY: warning_title")

    @property
    def what_language(self):
        """Default value: What language is it in? ({}/{})"""
        return self._text_data.get("what_language", "MISSING TEXT KEY: what_language")

    @property
    def which_glossary(self):
        """Default value: 
Which dictionary are you using?
 - {}
Choose: """
        return self._text_data.get("which_glossary", "MISSING TEXT KEY: which_glossary")

    @property
    def word_in_any_glossary(self):
        """Default value: This word is already in ANY dictionary! Are you..."""
        return self._text_data.get("word_in_any_glossary", "MISSING TEXT KEY: word_in_any_glossary")

    @property
    def word_in_current_glossary(self):
        """Default value: This word is already in this dictionary! Are yo..."""
        return self._text_data.get("word_in_current_glossary", "MISSING TEXT KEY: word_in_current_glossary")

    @property
    def yes_char(self):
        """Default value: y"""
        return self._text_data.get("yes_char", "MISSING TEXT KEY: yes_char")
