"""
Generates the langtext.py file based on JSON language files in language_learning/lib/assets/languages/.
Ensures all language files have the same keys and creates an enum for easy access.
"""

import json
import os
import sys

file_path = os.path.dirname(os.path.abspath(__file__))
# --- Configuration ---
LANG_DIR = os.path.join(file_path, "..", "lib", "assets", "languages")
APP_LANG_DIR = os.path.join("assets", "languages")
OUTPUT_FILE = "lib/langtext.py"


def load_language_files():
    """Loads all JSON files from the languages directory."""
    lang_data = {}

    if not os.path.exists(LANG_DIR):
        print(
            f"Error: Directory '{LANG_DIR}' not found. "
            "Please create it and place your language JSON files inside.",
            file=sys.stderr,
        )
        sys.exit(1)

    for filename in os.listdir(LANG_DIR):
        if filename.endswith(".json"):
            lang_name = os.path.splitext(filename)[0].upper()
            filepath = os.path.join(LANG_DIR, filename)
            try:
                with open(filepath, "r", encoding="utf-8") as f:
                    lang_data[lang_name] = json.load(f)
            except json.JSONDecodeError as e:
                print(f"Error reading JSON from {filepath}: {e}", file=sys.stderr)
                sys.exit(1)
            except Exception as e:
                print(
                    f"An unexpected error occurred while reading {filepath}: {e}",
                    file=sys.stderr,
                )
                sys.exit(1)

    if not lang_data:
        print(f"Error: No JSON files found in '{LANG_DIR}'.", file=sys.stderr)
        sys.exit(1)

    return lang_data


def validate_and_collect_keys(lang_data):
    """Validates that all language files have the same set of keys."""
    keys_by_lang = {name: set(data.keys()) for name, data in lang_data.items()}

    # Get the keys from the first language as the canonical set
    canonical_name = list(lang_data.keys())[0]
    canonical_keys = keys_by_lang[canonical_name]

    all_valid = True

    for lang_name, keys in keys_by_lang.items():
        if lang_name == canonical_name:
            continue

        missing_keys = canonical_keys - keys
        extra_keys = keys - canonical_keys

        if missing_keys:
            print(
                f"Error: Language '{lang_name}' is MISSING the following keys "
                f"compared to '{canonical_name}': {', '.join(sorted(missing_keys))}",
                file=sys.stderr,
            )
            all_valid = False

        if extra_keys:
            print(
                f"Error: Language '{lang_name}' has EXTRA keys not present in '{canonical_name}': "
                f"{', '.join(sorted(extra_keys))}",
                file=sys.stderr,
            )
            all_valid = False

    if not all_valid:
        print(
            "\nKey mismatch detected. Please fix the JSON files before regenerating langtext.py.",
            file=sys.stderr,
        )
        sys.exit(1)

    return sorted(list(canonical_keys))


def generate_langtext_py(lang_data: dict[str, dict[str, str]], keys: list[str]):
    """Generates the langtext.py file with the Lang enum and LangText class."""

    # Start of the file content
    content = [
        '"""This file is AUTO-GENERATED by langgen.py. DO NOT EDIT DIRECTLY."""',
        "",
        "import json",
        "import os",
        "from enum import Enum",
        "",
        "",
        "class Lang(Enum):",
        '    """Enum representing available languages with their file paths."""',
    ]

    # 1. Generate Lang Enum
    for name in sorted(lang_data.keys()):
        # Enum members are generated from file names
        # (e.g., HUNGARIAN = 'assets/languages/hungarian.json')
        filename = os.path.join(APP_LANG_DIR, name.lower() + ".json").replace("\\", "/")
        content.append(f'    {name} = "{filename}"')

    class_gen = '''
    def text(self):
        """Returns a LangText instance for this language."""
        return LangText(self)'''
    content.extend(class_gen.split("\n"))

    content.extend(
        [
            "",
            "",
            "class LangText:",
            '    """Dynamically loads language texts based on the selected Lang enum value."""',
            "",
            "    def __init__(self, lang_enum: Lang):",
            "        self._text_data = {}",
            "        lang_path = lang_enum.value",
            "        try:",
            "            if not os.path.isabs(lang_path):",
            "                lang_path = os.path.join(",
            "                    os.path.dirname(os.path.abspath(__file__)),",
            "                    lang_path,",
            "                )",
            "            # The value of the enum is the filepath",
            '            with open(lang_path, "r", encoding="utf-8") as f:',
            "                self._text_data = json.load(f)",
            "        except FileNotFoundError:",
            '            print(f"ERROR: Language file {lang_path} not found.")',
            "        except json.JSONDecodeError:",
            '            print(f"ERROR: Language file {lang_path} has invalid JSON.")',
            "",
            "    # 2. Generate properties for all keys",
        ]
    )

    # 2. Generate properties
    for key in keys:
        # Use property decorator to expose the text data fields dynamically
        content.append("    @property")
        content.append(f"    def {key}(self):")
        english_value = lang_data["ENGLISH"].get(key, "?")
        if len(english_value) > 50:
            english_value = english_value[:47] + "..."
        content.append(f'        """Default value: {english_value}"""')
        content.append(
            f'        return self._text_data.get("{key}", "MISSING TEXT KEY: {key}")'
        )
        content.append("")

    # Write the generated content to the output file
    try:
        with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
            f.write("\n".join(content))
        print(
            f"Successfully generated {OUTPUT_FILE} with {len(keys)} keys "
            f"from {len(lang_data)} languages."
        )
    except Exception as e:
        print(f"Error writing to {OUTPUT_FILE}: {e}", file=sys.stderr)
        sys.exit(1)


def generate_language_setup():
    """Main function to generate the language setup file."""
    print("Starting language configuration generation...")

    # Create the languages directory if it doesn't exist (helpful for initial setup)
    if not os.path.exists(LANG_DIR):
        os.makedirs(LANG_DIR)

    lang_data = load_language_files()
    keys = validate_and_collect_keys(lang_data)
    generate_langtext_py(lang_data, keys)


if __name__ == "__main__":
    generate_language_setup()
